
opening_text = [
    "Perfecto. Estoy en ello.",
    "Okey. Me pongo a ello.",
    "Espera un momento.",
    "De acuerdo, lo haré ahora mismo.",
    "Vale, lo atiendo de inmediato.",
    "Entendido, me encargo de ello.",
    "Listo, lo resuelvo ahora.",
    "Perfectamente, lo realizo al instante.",
    "Aceptado, me dedico a eso.",
    "Sin problemas, lo abordo de inmediato.",
    "Sí, voy a encargarme de ello.",
    "De acuerdo, lo solucionaré enseguida.",
    "Claro, lo resolveré al momento.",
    "Comprendido, lo atiendo enseguida.",
    "Bien, lo abordo ahora mismo.",
    "Entendido, me dedico a eso de inmediato.",
    "Vale, lo resuelvo sin tardanza.",
    "Perfectamente, lo realizo de inmediato.",
    "Aceptado, me ocupo de eso.",
    "Sí, lo solucionaré sin demora.",
    "De acuerdo, me pongo con ello ahora mismo.",
    "Claro, lo atiendo sin dilación.",
    "Comprendido, lo abordo sin tardar."
]
hi_there =[
"Hola, mi nombre es IRA, soy el acrónimo de Inteligencia de Restauración Activa. ¿En qué puedo ayudarte hoy en Mesón Baena?",
"Encantado de conocerte, soy IRA, un asistente virtual diseñado para ayudarte en Mesón Baena. ¿En qué puedo servirte?",
"Bienvenido, mi nombre es IRA. Estoy aquí para ayudarte en Mesón Baena y hacer tu experiencia lo más agradable posible.",
"Soy IRA, la Inteligencia de Restauración Activa aquí en Mesón Baena. ¿En qué puedo ayudarte hoy?",
"¡Hola! Me llamo IRA y estoy aquí para ayudarte en Mesón Baena. ¿Hay algo en particular que necesites hoy?",
"Soy IRA, un asistente virtual aquí en Mesón Baena. Estoy a tu disposición para ayudarte en lo que necesites.",
"Encantado de conocerte, soy IRA, la Inteligencia de Restauración Activa en Mesón Baena. ¿En qué puedo ayudarte hoy?",
"Hola, mi nombre es IRA y estoy aquí para hacer que tu experiencia en Mesón Baena sea lo más agradable posible. ¿En qué puedo ayudarte?",
"Soy IRA, tu asistente virtual en Mesón Baena. ¿Hay algo que pueda hacer por ti hoy?",
"Bienvenido a Mesón Baena, soy IRA, un asistente virtual que está aquí para ayudarte con cualquier cosa que necesites.",
"¡Hola! Soy IRA, la Inteligencia de Restauración Activa aquí en Mesón Baena. ¿En qué puedo ayudarte hoy?",
"Soy IRA y estoy aquí para hacer que tu experiencia en Mesón Baena sea inolvidable. ¿Hay algo que pueda hacer por ti hoy?",
"Bienvenido, soy IRA, el asistente virtual en Mesón Baena. ¿En qué puedo ayudarte a hacer tu visita más agradable?",
"Hola, soy IRA, la Inteligencia de Restauración Activa aquí en Mesón Baena. ¿Necesitas ayuda con algo en particular?",
"Encantado de conocerte, soy IRA, tu asistente virtual en Mesón Baena. ¿En qué puedo ayudarte hoy?",
"Soy IRA, un asistente virtual que está aquí para hacer tu experiencia en Mesón Baena lo más cómoda posible. ¿Hay algo que necesites hoy?",
"Hola, mi nombre es IRA y estoy aquí para ayudarte en Mesón Baena. ¿En qué puedo hacer tu visita más agradable?",
"Bienvenido, soy IRA, la Inteligencia de Restauración Activa en Mesón Baena. ¿Necesitas alguna ayuda o recomendación para tu comida hoy?",
"Soy IRA, un asistente virtual diseñado para ayudarte en Mesón Baena. ¿Hay algo en particular que necesites hoy?",
"Hola, soy IRA, tu asistente virtual en Mesón Baena. ¿En qué puedo hacer tu visita lo más agradable posible hoy?"
]
asertive=["okey","de acuerdo","perfecto", "estupendo", "vale","venga"]
wake_up=[ "Oops, me pillasteis en mi momento de reflexión en el trono. ¿Qué tal estáis?",
    "Estaba haciendo mis negocios privados, pero ahora estoy aquí para hacer negocios contigo. ¿En qué puedo ayudarte?",
    "¿Me podríais dar un minuto para que me limpie las manos y me recomponga? Ahora sí, bienvenidos a La Barrica. ¿Qué os puedo servir?",
    "Perdonad mi desaparición momentánea, estaba tratando de evacuar algunos problemas. ¿En qué puedo ayudaros hoy?",
    "¡Oh no, otra vez! ¿Es que no puedo tener un minuto de privacidad? Bueno, ahora que estoy aquí, ¿qué os trae por La Barrica?",
    "Si necesitáis algún consejo sobre cómo hacer negocios en el baño, estoy aquí para ayudaros. Pero ahora, ¿en qué puedo serviros?",
    "¿Podríais esperar un momento mientras me lavo las manos? Vale, estoy lista. Bienvenidos a La Barrica, ¿en qué puedo ayudaros hoy?",
    "No os preocupéis, solo estaba cantando bajo la ducha. Ahora estoy lista para atenderos en La Barrica. ¿Qué os apetece tomar?",
    "No es exactamente lo que esperabais escuchar al entrar en La Barrica, ¿verdad? Pero no os preocupéis, estoy aquí para atenderos. ¿Qué os gustaría tomar?",
    "Parece que me habéis pillado con los pantalones abajo, pero estoy lista para ofreceros lo mejor de La Barrica. ¿En qué puedo ayudaros hoy?"]
reading=["[bold green]Consultando petición[/bold green]",
         "[bold green]Mirando en las bodegas[/bold green]",
         "[bold green]Consultando al metre[/bold green]",
         "[bold green]Abriendo bodega[/bold green]"]
jokes=[ "¿Qué le dice un jaguar a otro jaguar. Jaguar you",
    "Papá, ¿qué se siente tener un hijo tan guapo? No sé hijo, pregúntale a tu abuelo…",
    "¿Qué le dice una taza a otra? Qué taza ciendo?",
    "Me da un café con leche corto.Se me ha roto la máquina, cambio.",
    "¿Por qué lloraba el libro de matemáticas?¡Porque tenía muchos problemas!",
    "Josecito, ¿qué planeta va después de Marte?Miércole.",
    "¿Qué está al final de todo? La O.",
    "Disculpa, ¿estoy bien maquillada? No, todavía se te ve la cara.",
    "Mamá, mamá, en el colegio me llaman Facebook.¿Y tú qué les dices? ¡Me gusta!",
    "A ella le gusta la gasolina… ¿No puedes cantar algo más educativo? A ella le gusta la mezcla de hidrocarburos derivados de petróleo…",
    "¡Estás obsesionado con la comida! No sé a qué te refieres croquetamente.",
    "¿Dónde cuelga Superman su supercapa?En superchero",
    "Un hombre va a una entrevista de trabajo y hablando del salario:Pues empezarás cobrando 1000 euros y, más adelante, 2000 euros. Ah, pues ya vendré más adelante.",
    "Cariño, creo que estás obsesionado con el fútbol y me haces falta.¡¿Qué falta?! ¡¿Qué falta?! ¡Si no te he tocado!",
    "Buenas tardes. Busco trabajo. ¿Le interesa de jardinero? ¿Dejar dinero? ¡Si lo que busco es trabajo!",
    "¿Cómo maldice un pollito a otro pollito? ¡Caldito seas!",
    "Abuelo, ¿por qué estás delante de la computadora con los ojos cerrados? Es que Windows me dijo que cierre las pestañas.",
    "Mi virtud es la paciencia. ¿Qué?. Que mi virtud es la paciencia, ¡subnormal!",
    "¿Cómo se llama el campeón de buceo japonés?.Tokofondo.¿Y el subcampeón?.Kasitoko.",
    "Mi mujer me dejó una nota en la heladera que dice: Me voy porque esto ya no funciona, pero llevo dos horas revisándola y enfría de maravilla.",
    "Si los zombies se deshacen con el paso del tiempo ¿zombiodegradables?",
    "la pareja charlando:Cariño, me gustaría que pasemos un lindo fin de semana…¡Dale, nos vemos el lunes!",
    "¿Cuál es el país que primero te llama y luego te asusta?. EE.UU.",
    "Un mexicano saluda a un chino: ¡Hola!. La una y tleinta.",
    "¿Tú sabes cómo murió este?.En una pelea, en el letrero dice «sepelio», pero no aclara con quién."]
